services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: "${DB_PORT}"
      POSTGRES_INITDB_SCRIPT: "./sql/schema.sql"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "${DB_PORT}:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # edunexus:
  #   container_name: "edunexus_container"
  #   build:
  #     context: "."
  #     dockerfile: Dockerfile
  #   environment:
  #     DB_NAME: "${DB_NAME}"
  #     DB_USERNAME: "${DB_USERNAME}"
  #     DB_PASSWORD: "${DB_PASSWORD}"
  #     DB_PORT: "${DB_PORT}"
  #     DB_HOST: "${DB_HOST}"
  #   ports:
  #     - "8080:8080"


volumes:
  pgadmin-data:
  postgres_data:
