// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: misc.sql

package db

import (
	"context"
)

const getModuleId = `-- name: GetModuleId :one
select id from modules where course_id = $1 and title = $2
`

type GetModuleIdParams struct {
	CourseID int64  `json:"course_id"`
	Title    string `json:"title"`
}

func (q *Queries) GetModuleId(ctx context.Context, arg GetModuleIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, getModuleId, arg.CourseID, arg.Title)
	var id int64
	err := row.Scan(&id)
	return id, err
}
